modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="ultracell"
version="1.0.0"
displayName="Ultra Cell"
authors="Nasilap"
description='''Large capacity FE storage cells for AppliedFlux. AE2 network only, no NeoForge energy capability.'''
logoFile="wuji_fe_cell.png"

[[dependencies.ultracell]]
modId="neoforge"
type="required"
versionRange="[21.1.251,)"
ordering="NONE"
side="BOTH"

[[dependencies.ultracell]]
modId="minecraft"
type="required"
versionRange="1.21.1"
ordering="NONE"
side="BOTH"

[[dependencies.ultracell]]
modId="ae2"
type="required"
versionRange="[19.2.17,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ultracell]]
modId="appflux"
type="required"
versionRange="[1.21-2.1.5-neoforge,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ultracell]]
modId="megacells"
type="required"
versionRange="*"
ordering="AFTER"
side="BOTH"